### ISSUE TITLE
error running reproducer.py example, but printed cmd runs fine.

### ISSUE THREAD

**Issue by perissology** [holiman/evmlab#20]
I'm trying to run the example ```python reproducer.py -g holiman/gethvm --hash 0xd6d519043d40691a36c9e718e47110309590e6f47084ac0ec00b53718e449fd3```

However I get the error ```Odd line: Fatal: invalid genesis file: read /var/folders/dl/xk24gkxd7xd6rs1gqdcnz0y00000gn/T/0xd6d519-genesis-geth_j6ug64o6.json: is a directory```.

If I run the outputted cmd ```docker run --rm -v /Users/me/evmlab/output//0xd6d519-genesis-geth_ue9q411b.json:/Users/me/evmlab/output//0xd6d519-genesis-geth_ue9q411b.json holiman/gethvm --prestate /Users/me/evmlab/output//0xd6d519-genesis-geth_ue9q411b.json --gas 150000 --sender 0x69ea6b31ef305d6b99bb2d4c9d99456fa108b02a --receiver 0xb97048628db6b661d4c2aa833e95dbe1a905b280 --input a9059cbb0000000000000000000000008eef795fd9150f118bddeca556a5a2a2438ab865000000000000000000000000000000000000000000000081ebd8ffd6b2a58000 --json run```

it will successfully print the traces.

any ideas why geth thinks `/var/folders/dl/xk24gkxd7xd6rs1gqdcnz0y00000gn/T/0xd6d519-genesis-geth_j6ug64o6.json` is a directory? If I cat the file, it is the genesis json

**Comment by holiman** [comment]
Hm, seems to work for me (note, though, using `python3`): 
```
#python3 reproducer.py -g holiman/gethvm --hash 0xd6d519043d40691a36c9e718e47110309590e6f47084ac0ec00b53718e449fd3
Setting Spurious config for block 4168497
GetAccountInfo(0xb97048628db6b661d4c2aa833e95dbe1a905b280, 4168497)
GetAccountInfo(0x69ea6b31ef305d6b99bb2d4c9d99456fa108b02a, 4168497)
Executing tx...
Saved trace to /tmp/0xd6d519_1xgfdic0.txt
SLOTS to fetch: {('0xb97048628db6b661d4c2aa833e95dbe1a905b280', '0x8')} 
GetStorageSlot(0xb97048628db6b661d4c2aa833e95dbe1a905b280, 8, 4168497)
Executing tx...
Saved trace to /tmp/0xd6d519_cetozk2t.txt
SLOTS to fetch: {('0xb97048628db6b661d4c2aa833e95dbe1a905b280', '0x485187f4b622765d9b1927b78eb228cda41c3bc6099b8e880c689fca05667af7')} 
GetStorageSlot(0xb97048628db6b661d4c2aa833e95dbe1a905b280, 32710578043407046683120320729771766219404884488826166225669873074870063364855, 4168497)
Executing tx...
Saved trace to /tmp/0xd6d519_mm_pv62x.txt
SLOTS to fetch: {('0xb97048628db6b661d4c2aa833e95dbe1a905b280', '0xc3efb091dd324c4381570d4ed1ffe61df0b62179cc8bddd0fb9bbc0495aff6bc')} 
GetStorageSlot(0xb97048628db6b661d4c2aa833e95dbe1a905b280, 88624500562062989280384220093372487239222897851773489223401442960595825456828, 4168497)
Executing tx...
Saved trace to /tmp/0xd6d519_rgjqnu62.txt
Final execution (memory on)
Saved trace to /tmp/0xd6d519_lv5syikm.txt
vm args:
{'json': True, 'gas': 150000, 'genesis': '/tmp/0xd6d519-genesis-geth_e6lo5bf7.json', 'receiver': '0xb97048628db6b661d4c2aa833e95dbe1a905b280', 'input': 'a9059cbb0000000000000000000000008eef795fd9150f118bddeca556a5a2a2438ab865000000000000000000000000000000000000000000000081ebd8ffd6b2a58000', 'sender': '0x69ea6b31ef305d6b99bb2d4c9d99456fa108b02a', 'memory': True}
Saving files

* annotated trace -> /home/martin/workspace/evmlab/output/0xd6d519_wp759pl2.evmtrace.txt
* json-trace -> /home/martin/workspace/evmlab/output/0xd6d519_lv5syikm.txt
* geth genesis -> /home/martin/workspace/evmlab/output/0xd6d519-genesis-geth_e6lo5bf7.json
* parity genesis -> /home/martin/workspace/evmlab/output/0xd6d519-genesis-parity_ftuupt_1.json

Command to execute locally (geth):

docker run --rm -v /home/martin/workspace/evmlab/output//0xd6d519-genesis-geth_e6lo5bf7.json:/home/martin/workspace/evmlab/output//0xd6d519-genesis-geth_e6lo5bf7.json holiman/gethvm --prestate /home/martin/workspace/evmlab/output//0xd6d519-genesis-geth_e6lo5bf7.json --gas 150000 --sender 0x69ea6b31ef305d6b99bb2d4c9d99456fa108b02a --receiver 0xb97048628db6b661d4c2aa833e95dbe1a905b280 --input a9059cbb0000000000000000000000008eef795fd9150f118bddeca556a5a2a2438ab865000000000000000000000000000000000000000000000081ebd8ffd6b2a58000 --json run

With memory:

docker run --rm -v /home/martin/workspace/evmlab/output//0xd6d519-genesis-geth_e6lo5bf7.json:/home/martin/workspace/evmlab/output//0xd6d519-genesis-geth_e6lo5bf7.json holiman/gethvm --prestate /home/martin/workspace/evmlab/output//0xd6d519-genesis-geth_e6lo5bf7.json --gas 150000 --sender 0x69ea6b31ef305d6b99bb2d4c9d99456fa108b02a --receiver 0xb97048628db6b661d4c2aa833e95dbe1a905b280 --input a9059cbb0000000000000000000000008eef795fd9150f118bddeca556a5a2a2438ab865000000000000000000000000000000000000000000000081ebd8ffd6b2a58000 --json run

For benchmarking:

docker run --rm -v /home/martin/workspace/evmlab/output//0xd6d519-genesis-geth_e6lo5bf7.json:/home/martin/workspace/evmlab/output//0xd6d519-genesis-geth_e6lo5bf7.json holiman/gethvm --prestate /home/martin/workspace/evmlab/output//0xd6d519-genesis-geth_e6lo5bf7.json --gas 150000 --sender 0x69ea6b31ef305d6b99bb2d4c9d99456fa108b02a --receiver 0xb97048628db6b661d4c2aa833e95dbe1a905b280 --input a9059cbb0000000000000000000000008eef795fd9150f118bddeca556a5a2a2438ab865000000000000000000000000000000000000000000000081ebd8ffd6b2a58000 --nomemory --statdump run

For opviewing:

python3 opviewer.py -f /home/martin/workspace/evmlab/output//0xd6d519_lv5syikm.txt

Zipped files into /home/martin/workspace/evmlab/output/0xd6d519.zip

```

I suspect that it's a discrepancy as to how `docker` interprets the `v` volume-mount command. It seems to mount the file as a folder. What OS and docker version are you using?

**Comment by perissology** [comment]
ya, my `python` maps to `python3` in the venv I'm using. 

python 3.5.1
Docker version 17.10.0-ce, build f4ffd25
osx 10.12.6

**Comment by holiman** [comment]
I think that's a mac-specific issue, I recall having seen that before. It would probably work if it instead was invoked with volume-mounting the folder, and not the file. Like so: 
```
docker run --rm -v /Users/me/evmlab/output/:/Users/me/evmlab/output/ holiman/gethvm --prestate /Users/me/evmlab/output//0xd6d519-genesis-geth_ue9q411b.json --gas 150000 --sender 0x69ea6b31ef305d6b99bb2d4c9d99456fa108b02a --receive
```

**Comment by perissology** [comment]
if I run the docker cmd directly, it works fine mounting the file or the folder. It's only when the docker cmd is run from `reproducer.py` does it give me the error

**Comment by holiman** [comment]
I think it may be due to shell or not shell when calling subprocess. I'll make a change to mount the folder instead, should work better in any case

**Comment by holiman** [comment]
Please test now, hopefully works better

**Comment by perissology** [comment]
no luck.

Still get the error...
```
python reproducer.py -g holiman/gethvm --hash 0xd6d519043d40691a36c9e718e47110309590e6f47084ac0ec00b53718e449fd3
Setting Spurious config for block 4168497
GetAccountInfo(0x69ea6b31ef305d6b99bb2d4c9d99456fa108b02a, 4168497)
GetAccountInfo(0xb97048628db6b661d4c2aa833e95dbe1a905b280, 4168497)
Executing tx...
Saved trace to /var/folders/dl/xk24gkxd7xd6rs1gqdcnz0y00000gn/T/0xd6d519_gconikre.txt
Odd line: Fatal: Failed to read genesis file: open /var/folders/dl/xk24gkxd7xd6rs1gqdcnz0y00000gn/T/0xd6d519-genesis-geth_ald57nj9.json: no such file or directory
```

**Comment by holiman** [comment]
So the evm generates some files using `tempfile.mkstemp` here: https://github.com/holiman/evmlab/blob/master/evmlab/genesis.py#L225 . 
It seems that on mac, those become placed in `/var/folders/dl....`. Could you check the permissions on that file? I'm thinking that maybe the docker daemon cannot read it, and thus fails to mount it ... 

After N runs, it copies the resulting genesis to `output`, where perhaps the permissions are different, hence why it works when you run the final result.

**Comment by holiman** [comment]
Changed to create files explicitly in the system temp-folder. Hopefully resolves the issue.

**Comment by perissology** [comment]
unfortunately, no luck.

644 permissions on the tmp file

**Comment by perissology** [comment]
this issue has to do with how osx shares folders with docker.

note: you need to use `docker for mac` instead of `docker toolbox` as `docker for mac` adds `/private` to the shared folders with docker

see for more context https://stackoverflow.com/a/45123074
