### ISSUE TITLE
reproducer.py fails to reproduce contract deploys

### ISSUE THREAD

**Issue by perissology** [holiman/evmlab#29]
If I pass a txHash for a contract deployment into `reproducer.py` it will fail. I have a fixed this locally, but since I'm still a bit unfamiliar w/ traces, I have a question regarding storage...

For a contract deployment, do I need to fetch the storage slots for the new contract? I don't think it is necessary, as the storage will be empty since it's a new contract, but thought I'd check before submitting a PR.

**Comment by holiman** [comment]
> For a contract deployment, do I need to fetch the storage slots for the new contract? 

No, that should not be necessary!
