### ISSUE TITLE
ImportError: cannot import name 'RPCProvider'

### ISSUE THREAD

**Issue by ansermino** [holiman/evmlab#48]
I'm trying to run the opviewer but am facing issues with web3:
```
python3 opviewer.py -f test.json
Traceback (most recent call last):
  File "opviewer.py", line 6, in <module>
    from evmlab import reproduce, utils
  File "/home/david/dev/evmlab/evmlab/reproduce.py", line 18, in <module>
    from web3 import Web3, RPCProvider
ImportError: cannot import name 'RPCProvider'
```
 I suspect there has been some changes to their code base which are yet to be reflected here. Haven't been able to find much on RPCProvider in the web3 docs. Tried reinstalling packages, pip3, and python3. These are the steps I took to install and run:
```
git clone https://github.com/holiman/evmlab/ && cd evmlab
pip3 install -r requirements.txt
evm --code 6001 --json >> test.json
python3 opviewer.py -f test.json
```

Output of `pip3 list` (some packages omitted:
```
docker (3.2.1)
Flask (0.12.2)
requests (2.18.4)
rlp (0.6.0)
urwid (2.0.1)
web3 (4.1.0)
```

Running Ubuntu 16.04.

**Comment by ansermino** [comment]
Issues is over a month old. Seems the code base has been updated to the latest version of web3. Thanks!

**Comment by BeOleg** [comment]
Same issue here
