### ISSUE TITLE
pin rlp version

### ISSUE THREAD

**Issue by pipermerriam** [holiman/evmlab#50]
FYI

the `rlp` library recently had a `1.0.0` release which introduced a number of breaking changes from the `<1.0` version.  You might want to pin your `requirements.txt` to `<1.0` **or** better, upgrade to the `>=1.0` version because it contains a lot of API and speed improvements.

**Comment by holiman** [comment]
actually, there are only a couple of things that evmlab needs, I think basically only deriving the contract address. That needs some tiny rlp-encoding (which could be hardcoded) plus `sha3`/`keccak`. It might be even better to base it off of py-evm. Can you point me to where you're loading that code from?

**Comment by pipermerriam** [comment]
If you're using py-evm you can use https://github.com/ethereum/py-evm/blob/master/evm/utils/address.py#L12-L13 but I wouldn't recommend importing it directly.  Anything under a `utils` namespace in our repositories is not public API and is subject to breaking changes without a deprecation cycle.  Small enough that vendoring it into your codebase should be fine.

**Comment by holiman** [comment]
You're using  `from eth_hash.auto import keccak` -- I'm not totally sure what project that's imported from. 

Pyetherem seems to be using `pycryptodome` (requirements.txt:)
```
py_ecc
pyethash>=0.1.27,<1.0.0
pycryptodome>=3.4.7
```

I think I'll skip `rlp` and use `pycryptodome` to get `keccak`, and hardcode the tiny rlp encoding needed to calculate a contract address.

**Comment by pipermerriam** [comment]
So `eth-hash` is a library we wrote to abstract away the actual keccak implementation.  It supports both pycryptodome and pysha3 for backends as well as the use providing their own backend.

not to be confused with `pyethash` which is the POW mining library.

If you want to install `eth-hash` with one of the backends do `pip install eth-hash[pycryptodome]` or `pip install eth-hash[pysha3]`

**Comment by pipermerriam** [comment]
https://github.com/ethereum/eth-hash

**Comment by holiman** [comment]
This has been fixed, and I also fixed up the docker image and configured it as an automatic build on docker hub (holiman/evmlab). Thanks @pipermerriam !
